#note: largely following xdem example
# left 'files: ' blank, wasn't sure how to specify yet
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
        exclude: ^data/
      - id: check-executables-have-shebangs
        exclude: ^data/
      - id: check-json
        exclude: ^data/
      - id: check-merge-conflict
        exclude: ^data/
      - id: check-symlinks
        exclude: ^data/
      - id: check-toml
        exclude: ^data/
      - id: check-vcs-permalinks
        exclude: ^data/
      - id: check-yaml
        exclude: ^data/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        exclude: ^data/
      - id: end-of-file-fixer
        exclude: ^data/
      - id: trailing-whitespace
        exclude: ^data/
      - id: check-merge-conflict
        exclude: ^data/

  # Fix common spelling mistakes
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
      - id: codespell
        args: ["--check-filenames"]
        types_or: [python, yaml, markdown]
        exclude: ^data/

  # Replace relative imports
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        exclude: ^data/

  # Format code using black
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [--line-length=120]
        exclude: ^data/

  # Lint code using flake8
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: ^data/
        args: [
          '--max-line-length', '120',
          '--extend-ignore', 'E203,C408',
          '--'
        ]
        additional_dependencies:
          - flake8-comprehensions==3.1.0
          - flake8-bugbear==21.3.2

  # Sort imports using isort
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^data/
        args: ["--profile", "black"]

  # Automatically upgrade syntax to a minimum version
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
        exclude: ^data/
        args: [--py37-plus]

  # Various formattings
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: rst-backticks
        exclude: ^data/
      - id: rst-directive-colons
        exclude: ^data/
        types: [text]
        types_or: [python, rst]
      - id: rst-inline-touching-normal
        exclude: ^data/
        types: [text]
        types_or: [python, rst]
      - id: python-no-eval
        exclude: ^data/
      - id: python-use-type-annotations
        exclude: ^data/
