name: itslivetools_env
channels: 
 - conda-forge
dependencies:
- distributed
- cartopy
- flox
- gdal
- geocube
- geopandas
- geoviews
- hvplot
- pyarrow
- pip
- python
- matplotlib-base
- rioxarray
- scikit-image
- seaborn
- shapely
- s3fs
- zarr
# For development
- jupyter-book
- jupyterlab
- sphinxext-opengraph 
